# Generated by Django 5.0.4 on 2026-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment_confirmed', 'Programare Confirmată'), ('appointment_cancelled', 'Programare Anulată'), ('technician_en_route', 'Tehnician în drum'), ('appointment_completed', 'Programare Finalizată'), ('review_request', 'Lasă un Review'), ('new_task', 'Task Nou Primit'), ('reminder', 'Reminder Programare')], max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_appointment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
