# Generated by Django 5.0.4 on 2026-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='problem_description',
            field=models.TextField(blank=True),
        ),
    ]
