# Generated by Django 5.0.4 on 2026-06-03 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianschedule',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='technicians.technician'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianschedule',
            unique_together={('technician', 'day_of_week')},
        ),
    ]
